language: ruby
rvm:
  - 2.4.3
  - 2.5.0

cache:
  directories:
    - vendor/bundle

before_script:
  - bundle install --path vendor/bundler --jobs 4

script:
  - bundle exec rspec

notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
    secure: "cktojGxYvyaYYJ+izURVqO1l+JStXpkOXI3Js/ZMzk+s9NkShE/dHeNQcwkpqdj+vy3lme+doSR1/02+zh3VUFJ1nll/SzhflX3r/sTRa9k3vd1iQNUMJmzX57daxH6zn9TgvL8L4fTq0i5EdgMqGZk3DieWxS6C0QEqS/5jtSov/hL7h+99w6eDC/pAYXi9UpqkOKjh47O2u046gXGI+k/m0gljCyMpU5k4xDUDPktYfF9SxbC659M+pBGegUsvLcT7BkiediNO7iazYqQ9aEjSa9XwMQcleJHwPxqImaK9YKRgbXqzrEYWS9m04cV9pA3fUv/VXifo/PVIL63Q8S/tKlqdwbksX+yfBlfIoE6RpogK2H30427q+V2x+wtef0ohJznSBSfg8LyAi3z+4Q9tqaUTMAZaj5x684jsOAduYBo0QAIu62JrMzwGY1+nnEwTmcfNevRCr3SsXVBNNrB63sS75kToc/HfuTQG7hS4ds2hXrCrmIiPicnxsZ1ebe4ilZjFKw5kjyGdXD6ke1qkAX5aWrtE1ehCo45TknJNdtP3+gYy3E72sqdhRGHiodEWq8LX0kLhwTZcUK9oVhvUqVAyQSq3vY629mPlmYG5M34S3xxJkbdsBLG+E7eJJAhcqoD1MK0fkeuc0NSd6St7KLJLsw5yIcjr7DJKOVo="
