accounts:
  -
    # Account name.
    name: ''

    # Twitter keys.
    consumer_key: ''
    consumer_secret: ''
    access_token: ''
    access_token_secret: ''

    # List id (Integer)
    list_id : ''

  -
    name: ''
    consumer_key: ''
    consumer_secret: ''
    access_token: ''
    access_token_secret: ''
    list_id : ''
